name: Unit Tests

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  merge_group:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  FOUNDRY_PROFILE: ci

jobs:
  contracts-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup
        uses: ./.github/actions/setup

      - name: Run Forge build
        run: |
          just build-contracts
        id: build

      - name: Run Forge tests
        run: |
          just test-contracts
        id: test
  
  go-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup
        uses: ./.github/actions/setup

      - name: Install dependencies
        run: go mod download

      - name: Run tests
        run: just test-go
